apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi-operator
  namespace: kafka
spec:
  helmVersion: v3
  releaseName: strimzi-kafka-operator
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.22.1
  values:
    watchNamespaces: []
    watchAnyNamespace: true